from app.core.db import Base
from .user import User
from .cv import Cv
from .interview import Interview
from .question import Question
from .report import Report
from .answer import Answer
from .topic import Topic
from .question_topic_association import question_topic_table