"""Rename text column to content in Question table

Revision ID: 34e3bdd41610
Revises: caaf6d1a6c83
Create Date: 2025-10-02 18:16:51.119309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34e3bdd41610'
down_revision: Union[str, Sequence[str], None] = 'caaf6d1a6c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'text', new_column_name='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'content', new_column_name='text')
    # ### end Alembic commands ###
