"""Add a type column to the questions table

Revision ID: 3f47e8090031
Revises: de499a0d3bf8
Create Date: 2025-10-03 02:18:55.536155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f47e8090031'
down_revision: Union[str, Sequence[str], None] = 'de499a0d3bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Finds all rows where mode is NULL and sets them to 'easy'
    op.execute("UPDATE interviews SET mode = 'easy' WHERE mode IS NULL")

    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.alter_column('mode',
                              existing_type=sa.VARCHAR(length=6),
                              nullable=False,
                              # IMPORTANT: This handles existing rows that are NULL
                              server_default="easy")
    op.add_column('questions', sa.Column('type', sa.Enum('SITUATIONAL', 'TECHNICAL', 'BEHAVIOURAL', name='questiontype'),
                                          nullable=False, server_default='technical' ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'type')
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.alter_column('mode',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
    # ### end Alembic commands ###
