"""Add cascading to the tables

Revision ID: c688b0c3033a
Revises: 3e1b8cd3b05c
Create Date: 2025-10-04 21:10:00.800334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c688b0c3033a'
down_revision: Union[str, Sequence[str], None] = '3e1b8cd3b05c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
