"""rename the score column to final_score

Revision ID: caaf6d1a6c83
Revises: 1d12a55fdb75
Create Date: 2025-10-02 17:45:56.405260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caaf6d1a6c83'
down_revision: Union[str, Sequence[str], None] = '1d12a55fdb75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('final_score', sa.Float(), nullable=True))
    op.drop_column('interviews', 'score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('score', sa.FLOAT(), nullable=True))
    op.drop_column('interviews', 'final_score')
    # ### end Alembic commands ###
