"""adding a new columns to the report table

Revision ID: d876b22569c6
Revises: 799f70a051fb
Create Date: 2025-10-09 21:40:54.161993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd876b22569c6'
down_revision: Union[str, Sequence[str], None] = '799f70a051fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'uploaded_at')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', 
                                     sa.DateTime(timezone=True), 
                                     server_default=sa.func.now(), 
                                     nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('uploaded_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('created_at')
    # ### end Alembic commands ###
