"""Add a mode column to the interviews table

Revision ID: de499a0d3bf8
Revises: e68f6368a83a
Create Date: 2025-10-02 18:40:13.987904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de499a0d3bf8'
down_revision: Union[str, Sequence[str], None] = 'e68f6368a83a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('mode', sa.Enum('EASY', 'MEDIUM', 'HARD', name='interviewmode'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'mode')
    # ### end Alembic commands ###
