"""Drop the audio_path column from questions

Revision ID: e68f6368a83a
Revises: 34e3bdd41610
Create Date: 2025-10-02 18:19:07.447598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68f6368a83a'
down_revision: Union[str, Sequence[str], None] = '34e3bdd41610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'audio_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('audio_path', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
